version: "3"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${LOCAL_FILES_DIR}:/var/files
    ports:
      - "8080:8080"
    env_file:
      - .env
