version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Users/adrienblavier/Documents/settlemint/dxc/go-api:/var/files
    ports:
      - '8080:1323'
